{% set name = "mumps" %}
{% set version = "5.2.1" %}
{% set sha256 = "d988fc34dfc8f5eee0533e361052a972aa69cc39ab193e7f987178d24981744a" %}

package:
  name: mumps
  version: {{ version }}

source:
  fn: MUMPS_{{ version }}.tar.gz
  url: http://mumps.enseeiht.fr/MUMPS_{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - shared-pord.patch
    - shared-mumps.patch
    - shared-libseq.patch
    - examples-mpilibs.patch

build:
  number: 3

requirements:
  build:
    # dummy unused top-level requirements
    # needed to construct the right conda-smithy matrix
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - mpi * {{ mpi }}  # [mpi != 'nompi']

outputs:
  - name: mumps-include
    build:
      script: ${RECIPE_DIR}/build-headers.sh
      skip: true  # [win]
    requirements:
      build: []
      host: []
    test:
      commands:
        - test -f "${PREFIX}/include/mumps_compat.h"

  - name: mumps-seq
    build:
      script: ${RECIPE_DIR}/build-seq.sh  # [not win]
      script: "%RECIPE_DIR%\\bld-seq.bat"  # [win]
      run_exports:
        - {{ pin_subpackage('mumps-seq', max_pin='x.x.x') }}  # [not win]
      skip: true  # [mpi != 'nompi']
    requirements:
      build:
        - cmake  # [win]
        - m2-patch  # [win]
        - {{ compiler('fortran') }}        # [unix]
        - {{ compiler('m2w64_fortran') }}  # [win]
        - {{ compiler('c') }}        # [unix]
        - {{ compiler('m2w64_c') }}  # [win]
      host:
        - libblas
        - liblapack
        - metis  # [not win]
        - scotch  # [not win]
      run:
        - {{ pin_subpackage('mumps-include', max_pin='x.x.x') }}  # [not win]
        - metis  # [not win]
        - scotch  # [not win]

    test:
      commands:
        {% if not win %}

        {% for lib in [
          'smumps',
          'dmumps',
          'cmumps',
          'zmumps',
          'mumps_common',
          'pord',
        ] %}
        - test -f "${PREFIX}/lib/lib{{ lib }}_seq-{{ version }}${SHLIB_EXT}"
        - test -f "${PREFIX}/lib/lib{{ lib }}_seq${SHLIB_EXT}"
        - test -h "${PREFIX}/lib/lib{{ lib }}_seq${SHLIB_EXT}"
        {% endfor %}
        - test -f "${PREFIX}/lib/libmpiseq_seq-{{ version }}${SHLIB_EXT}"
        - test -f "${PREFIX}/lib/libmpiseq_seq${SHLIB_EXT}"
        - test -h "${PREFIX}/lib/libmpiseq_seq${SHLIB_EXT}"
        - test -f "${PREFIX}/lib/libmpiseq${SHLIB_EXT}"
        - test -h "${PREFIX}/lib/libmpiseq${SHLIB_EXT}"
        - test -f "${PREFIX}/include/mumps_seq/mpi.h"
        - test -f "${PREFIX}/include/mumps_seq/mpif.h"
        {% else %}
        - if not exist "%LIBRARY_PREFIX%\mingw-w64\bin\libsmumps.dll" exit 1
        - if not exist "%LIBRARY_PREFIX%\mingw-w64\bin\libdmumps.dll" exit 1
        - if not exist "%LIBRARY_PREFIX%\mingw-w64\bin\libcmumps.dll" exit 1
        - if not exist "%LIBRARY_PREFIX%\mingw-w64\bin\libzmumps.dll" exit 1
        - if not exist "%LIBRARY_PREFIX%\mingw-w64\lib\libmumps_common.a" exit 1
        - if not exist "%LIBRARY_PREFIX%\mingw-w64\lib\libpord.a" exit 1
        - if not exist "%LIBRARY_PREFIX%\mingw-w64\include\dmumps_struc.h" exit 1
        {% endif %}

  - name: mumps-mpi
    build:
      skip: true  # [win or mpi == 'nompi']
      script: ${RECIPE_DIR}/build-mpi.sh
      run_exports:
        - {{ pin_subpackage('mumps-mpi', max_pin='x.x.x') }}  # [not win]
      features:
    requirements:
      build:
        - {{ compiler('fortran') }}  # [not win]
        - {{ compiler('c') }}  # [not win]
      host:
        - libblas
        - liblapack
        - {{ mpi }}
        - metis
        - parmetis
        - ptscotch
        - scalapack
        - scotch
      run:
        - {{ pin_subpackage('mumps-include', exact=True) }}
        - {{ mpi }}
        - metis
        - parmetis
        - ptscotch
        - scalapack
        - scotch

    test:
      commands:
        {% for lib in [
          'smumps',
          'dmumps',
          'cmumps',
          'zmumps',
          'mumps_common',
          'pord',
        ] %}
        - test -f "${PREFIX}/lib/lib{{ lib }}-{{ version }}${SHLIB_EXT}"
        - test -h "${PREFIX}/lib/lib{{ lib }}${SHLIB_EXT}"
        - test -f "${PREFIX}/lib/lib{{ lib }}${SHLIB_EXT}"
        {% endfor %}
        - test ! -f "${PREFIX}/lib/libmpiseq*"
        - test ! -d "${PREFIX}/include/mumps_seq"

about:
  home: http://mumps.enseeiht.fr/
  license: CeCILL-C
  license_file: LICENSE
  summary: 'MUMPS: a parallel sparse direct solver'
  description: |
    MUMPS (MUltifrontal Massively Parallel Solver) is a package for solving
    systems of linear equations of the form Ax = b, where A is a square sparse
    matrix that can be either unsymmetric, symmetric positive definite, or
    general symmetric, on distributed memory computers. MUMPS implements a
    direct method based on a multifrontal approach which performs a Gaussian
    factorization.
  doc_url: http://mumps.enseeiht.fr/index.php?page=doc

extra:
  recipe-maintainers:
    - basnijholt
    - dalcinl
    - minrk
    - jbweston
