{% set name = "mumps" %}
{% set version = "5.0.2" %}
{% set sha256 = "77292b204942640256097a3da482c2abcd1e0d5a74ecd1d4bab0f5ef6e60fe45" %}
{% set variant = "openblas" %}

package:
  name: mumps
  version: {{ version }}

source:
  fn: MUMPS_{{ version }}.tar.gz
  url: http://mumps.enseeiht.fr/MUMPS_{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - mumps_mpi.patch

build:
  number: 203
  features:
    - blas_{{ variant }}
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py35]

requirements:
  build:
    - toolchain
    - metis
    - scotch
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*
    - gcc
    - python  # [win]
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]
  run:
    - metis
    - scotch
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*
    - libgfortran
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]

test:
  commands:
    - test -f "${PREFIX}/lib/libzmumps.a"  # [not win]
    - test -f "${PREFIX}/lib/libcmumps.a"  # [not win]
    - test -f "${PREFIX}/lib/libdmumps.a"  # [not win]
    - test -f "${PREFIX}/lib/libsmumps.a"  # [not win]
    - test -f "${PREFIX}/lib/libmumps_common.a"  # [not win]
    - test -f "${PREFIX}/lib/libpord.a"  # [not win]
    - test -f "${PREFIX}/lib/libmpiseq.a"  # [not win]
    - test -f "${PREFIX}/include/dmumps_struc.h"  # [not win]
    - test -f "${PREFIX}/include/zmumps_struc.h"  # [not win]
    - test -f "${PREFIX}/include/cmumps_struc.h"  # [not win]
    - test -f "${PREFIX}/include/smumps_struc.h"  # [not win]
    - test -f "${PREFIX}/include/mumps_mpi.h"  # [not win]
    - if not exist "%LIBRARY_LIB%\\libzmumps.lib" exit 1  # [win]
    - if not exist "%LIBRARY_LIB%\\libcmumps.lib" exit 1  # [win]
    - if not exist "%LIBRARY_LIB%\\libdmumps.lib" exit 1  # [win]
    - if not exist "%LIBRARY_LIB%\\libsmumps.lib" exit 1  # [win]
    - if not exist "%LIBRARY_LIB%\\libmumps_common.lib" exit 1  # [win]
    - if not exist "%LIBRARY_LIB%\\libpord.lib" exit 1  # [win]
    - if not exist "%LIBRARY_LIB%\\libmpiseq.lib" exit 1  # [win]
    - if not exist "%LIBRARY_INC%\\dmumps_struc.h" exit 1  # [win]
    - if not exist "%LIBRARY_INC%\\zmumps_struc.h" exit 1  # [win]
    - if not exist "%LIBRARY_INC%\\cmumps_struc.h" exit 1  # [win]
    - if not exist "%LIBRARY_INC%\\smumps_struc.h" exit 1  # [win]
    - if not exist "%LIBRARY_INC%\\mumps_mpi.h" exit 1  # [win]

about:
  home: http://mumps.enseeiht.fr/
  license: CeCILL-C
  license_file: LICENSE
  summary: 'MUMPS: a parallel sparse direct solver'
  description: |
    MUMPS (“MUltifrontal Massively Parallel Solver”) is a package for solving 
    systems of linear equations of the form Ax = b, where A is a square sparse 
    matrix that can be either unsymmetric, symmetric positive definite, or 
    general symmetric, on distributed memory computers. MUMPS implements a 
    direct method based on a multifrontal approach which performs a Gaussian 
    factorization.
  doc_url: http://mumps.enseeiht.fr/index.php?page=doc

extra:
  recipe-maintainers:
    - basnijholt
